### ISSUE TITLE
[FEATURE] - Creating an endpoint for api/login, api/teachers, api/delete, api/teachers-profile

### ISSUE THREAD

**Issue by taiwosunday99** [BuildForSDG/team-013-Backend#1]
Task 1

* Creating model for both Profile and Application Form with the appropriate endpoint and storage credentials.

* Repeat the task above for Approved Teachers

		Task 2

* Creating model for Sign In and Authenticate Users who signed in and logged out. 

* Repeat task above for Teachers Grade Point.

		Task 3

* Create an endpoint to collate Approved Teachers record and Teachers Grade Points.

* Create and endpoint that links to Source for Teachers.

**Comment by Theshedman** [comment]
## These are the tasks I have completed

- [x] I have implemented authorization and access control to all the endpoints for teachers

- [x]  Created endpoints for user Login and Registration. Note: user can log in with either their phone, email, or username in combination with their password

- [x]  Created an endpoint for updating user details, including image upload

- [x]  Created an endpoint for getting all the registered teachers in the platform

- [x]  Created an endpoint for getting only approved teachers

- [x]  Created an endpoint to delete teachers accounts

- [x]  Created an endpoint for getting teacher's profile

- [x]  Created an endpoint for deleting teacher's profile
